### ISSUE TITLE
dapr-hook failed when uninstalling multiple releases at once

### ISSUE THREAD

**Issue by KaiWalter** [dapr-sandbox/dapr-shared#43]
When uninstalling multiple releases at once, this error is logged

```
$ helm uninstall receiver-standard-dapr receiver-express-dapr distributor-dapr

release "receiver-standard-dapr" uninstalled
release "receiver-express-dapr" uninstalled
Error: 1 error occurred:
        * pod distributor-dapr-hook failed
```
 
looking into logs of the related `-dapr-hook` pod/container, it seems like a conflict in deletion of shared objects

```
$ kubectl logs pods/distributor-dapr-hook
2024/01/10 15:59:30 executing dapr-shared-init
panic: configmaps "distributor-dapr-cm" is forbidden: User "system:serviceaccount:default:distributor" cannot delete resource "configmaps" in API group "" in the namespace "default": RBAC: [clusterrole.rbac.authorization.k8s.io "dapr-shared-secret-reader" not found, clusterrole.rbac.authorization.k8s.io "dapr-shared-configmap-creator" not found]
Azure does not have opinion for this user.

goroutine 1 [running]:
main.RemoveHandler()
        /home/kai/src/dapr-shared/cmd/shared-init/main.go:148 +0xac
main.NewRemoveCmd.func1(0xc0003aa100?, {0x18d8cb1?, 0x4?, 0x18d8cb5?})
        /home/kai/src/dapr-shared/cmd/shared-init/main.go:96 +0xf
github.com/spf13/cobra.(*Command).execute(0xc00030ac00, {0xc0003842a0, 0x1, 0x1})
        /home/kai/.go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0xc00030a600)
        /home/kai/.go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /home/kai/.go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /home/kai/src/dapr-shared/cmd/shared-init/main.go:31 +0x8b
```

be aware, that I already had to "trick" release installation into multiple instances by overriding `fullnameOverride` and especially `shared.serviceAccount.name` to already avoid conflicts while installing

```
  apps=("distributor" "receiver-express" "receiver-standard")

  for app in "${apps[@]}"
  do
    echo "$app"

    # fork/branch: https://github.com/ZEISS/dapr-shared/tree/recycle-configmap
    helm upgrade --install $app-dapr $REPO_ROOT/../dapr-shared/chart/dapr-shared/ \
      --set fullnameOverride=$app-dapr \
      --set shared.initContainer.image.registry=$AZURE_CONTAINER_REGISTRY_ENDPOINT \
      --set shared.strategy=deployment \
      --set shared.scheduling.nodeSelector.agentpool=backend \
      --set shared.deployment.replicas=3 \
      --set shared.daprd.image.tag=1.11.6 \
      --set shared.appId=$app \
      --set shared.remoteURL=$app-svc \
      --set shared.remotePort=80 \
      --set shared.serviceAccount.name=$app \
      --set shared.daprd.listenAddresses=0.0.0.0

  done
```

**Comment by KaiWalter** [comment]
to add --- in deployed state the 3 instances (deployment) share the same `ClusterRole` 's

```
distributor-dapr-configmap-creator                      ClusterRole/dapr-shared-configmap-creator
distributor-dapr-secret-reader                         ClusterRole/dapr-shared-secret-reader
receiver-express-dapr-configmap-creator                 ClusterRole/dapr-shared-configmap-creator
receiver-express-dapr-secret-reader                    ClusterRole/dapr-shared-secret-reader
receiver-standard-dapr-configmap-creator                ClusterRole/dapr-shared-configmap-creator
receiver-standard-dapr-secret-reader                   ClusterRole/dapr-shared-secret-reader
```

**Comment by salaboy** [comment]
I wish we could remove that init-container.. as it will cause us too many headaches.. but for now we need to keep it to initialize the Trust Anchor. 

For now, having different cluster roles and serviceaccounts per shared instance sounds like a good approach to try out.

**Comment by salaboy** [comment]
Oh ok.. I see that you are setting the serviceAccountName. In that case you can disable the serviceAccount creation with 
`shared.serviceAccount.create=false`, @KaiWalter  would that fix the issue that you were hitting?

**Comment by salaboy** [comment]
@KaiWalter I managed to make progress.. but for some reason in my local cluster with my local helm version being v3.13.3 my delete hook is always failing due to the service account not being there for the hook Pod.. 
I remember that this was working correctly, and it seems to be working for you in your cluster.

**Comment by salaboy** [comment]
@KaiWalter this is done in v0.0.10 of the chart.. can you give it a try?

**Comment by KaiWalter** [comment]
> Oh ok.. I see that you are setting the serviceAccountName. In that case you can disable the serviceAccount creation with `shared.serviceAccount.create=false`, @KaiWalter would that fix the issue that you were hitting?

I used that setting not to use my own serviceAccount (avoiding create) but to make serviceAccount unique for each of the 3 instances. Is that required / is my assumption correct here?

**Comment by KaiWalter** [comment]
> @KaiWalter this is done in v0.0.10 of the chart.. can you give it a try?

v0.0.10 is just working fine - tested multiple installs & uninstalls

**Comment by salaboy** [comment]
Awesome! Thanks

 - Blog: http://salaboy.com <http://salaboy.wordpress.com>
 - Github user: http://github.com/salaboy
 - Twitter: http://twitter.com/salaboy

 - Mauricio "Salaboy" Salatino -
