### ISSUE TITLE
Maintain identity in ambient mode

### ISSUE THREAD

**Issue by JoshVanL** [dapr-sandbox/dapr-shared#8]
There is currently an [effort in dapr](https://github.com/dapr/dapr/issues/5899) to have strong identity. Ideally, ambient mode should maintain this security posture.

In ambient mode, daprd is installed as a daemon set where each dapr app connects to its node's daprd. That daprd must either 1. only allow apps which share the same app ID to connect, or 2. a single daprd should be able to serve any number of app IDs which are not necessarily known beforehand.

**Comment by salaboy** [comment]
For now, I am trying to get "1" done. For implementing 2 I think we will need to change `daprd` itself and that sounds like a big chunk of work. I hope the work on ambient will push us to have the right conversations around those changes.

**Comment by salaboy** [comment]
@JoshVanL after almost a year of you creating this issue.. now I understand why this is extremely important.. and I will close this issue because I am going to make sure that we keep 1 daprd <-> 1 app-id
